baseurl: '/blog'

# Markdown
markdown: kramdown

permalink: /:year/:month/:day/:title.html

# Navbar (EN)
nav:
  Docs: 'https://docs.neptune.work'
  
# Build settings
paginate: 6
paginate_path: 'page:num'
