baseurl: ''

# Markdown
markdown: kramdown

permalink: /blog/:year/:month/:day/:title

# Navbar (EN)
nav:
  Docs: 'https://docs.neptune.work'
  
# Build settings
paginate: 6
paginate_path: 'blog/page:num'

blog-header-bg-color: '120deg, #00458A, #01C1CE'
