baseurl: ''

# Markdown
markdown: kramdown

permalink: /blog/:year/:month/:day/:title

# Navbar (EN)
nav:
  Docs: 'https://docs.neptune.work',
  Blog: 'https://www.neptune.work/blog'
  
# Build settings
paginate: 6
paginate_path: 'blog/page:num'

